In [31]:
import pandas as pd
import os
# pd.set_option('display.max_rows', 500)
# pd.set_option('display.max_columns', 500)
pd.set_option('display.max_colwidth', -1)

<ipython-input-31-44aa353747c0>:5: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  pd.set_option('display.max_colwidth', -1)

In [27]:
cluster_data_path = '/home/manuto/Documents/world_bank/bert_twitter_labor/twitter-labor-data/data/evaluation_inference/clustering/US/iter_0-convbert-test-48-10-900-1538433-new_samples/kmeans'

## is_hired_1mo

In [28]:
df = pd.read_parquet(os.path.join(cluster_data_path, 'is_hired_1mo_7_clusters.parquet'))

In [29]:
df = df.groupby('cluster', group_keys=False).apply(lambda df: df.sample(3)).reset_index(drop=True)
df.shape

(21, 4)

In [32]:
df[['text', 'cluster']]

,text,cluster
0,I start school tomorrow tho 😊😊😊,0
1,start fresh every day,0
2,I started this new pushup challenge and I already hate myself,0
3,My first day back to work after a five day vacation 😩,1
4,I went to my first game last veterans day 😍❤️💛❤️💛,1
5,"Today is the first. A new day, a new month for self improvement :)",1
6,I'm getting a new job! 😁 https://t.co/1u4THYdY96,2
7,@Eatt_My_CupCaKe I got the job,2
8,Got the job. Now to get to work. Blue print reading http://t.co/g5KjsIp9yg,2
9,Start my new job on the 27th 💸,3
10,Can't believe I'm starting my new job tomorrow with a black eye😒,3
11,I start my new job tomorrow :)* hope I like it,3
12,yay!!! my new keyboard came!! :),4
13,im happy. new hair and I bought myself an iPad today. 🤗🙃😏 #feelingaccomplished https://t.co/lkRpwCjNCe,4
14,Finally got my BMW and it's everything 😍😍😍😍😍😍😍😍😍😍😍,4
15,We got paid for Memorial Day!!! WOOT WOOT!!!!,5
16,Got the 5th SnapBack !,5
17,I received my dealer license today!! Time to buy!!,5
18,finally finished the office:(((,6
19,Just finished day 2 at the gym.,6
20,Got off early 💃🏻,6

## lost_job_1mo

In [33]:
df = pd.read_parquet(os.path.join(cluster_data_path, 'lost_job_1mo_7_clusters.parquet'))

In [34]:
df = df.groupby('cluster', group_keys=False).apply(lambda df: df.sample(3)).reset_index(drop=True)
df[['text', 'cluster']]

,text,cluster
0,I lost my voice last Saturday. I still haven’t gotten it back yet. 🤦🏽‍♀️,0
1,I just lost the game. Fml.,0
2,"I lost four followers today. May not be a lot to any of you popular people, but I don't have friends. Lol.",0
3,I just got put inna really bad mood. Tbh,1
4,I just got pissed off all over again lmao,1
5,I just got pissed tf off man..,1
6,Just got outta bed👌,2
7,We just got kicked out our house lol,2
8,JUST GOT OUT OF SCHOOL !!,2
9,Just got flipped off driving for absolutely no reason... Awesome! Happy Saturday!!!!,3
10,I got called a ginger today... It really offended me.,3
11,"I got pulled over today. When I cracked the window, the officer asked me to roll it down further ""so that he could hear me""",3
12,I just walked home....enough said,4
13,Just got home. Just turned on the TV. MTV is on. Who is this performing lol I'm so confused.,4
14,Just got home. Great night.,4
15,i just got sick out of nowhere wtf,5
16,Just got super sick out of no where 😭,5
17,@_EastbankFinest 😂😂😂 shid ima see how I’m feeling. I got sick yesterday.,5
18,Just got run off Franklin Road by a truck. What the heck? Can't decide if trucks love or hate me #happytobeok,6
19,"It just hit me, I'm a junior in college.",6
20,Just got put on the back burner.,6

## is_unemployed

In [35]:
df = pd.read_parquet(os.path.join(cluster_data_path, 'is_unemployed_7_clusters.parquet'))

In [36]:
df = df.groupby('cluster', group_keys=False).apply(lambda df: df.sample(3)).reset_index(drop=True)
df[['text', 'cluster']]

,text,cluster
0,http://t.co/UiQ4EaVyxB\nI'm on the floor dying!!!!,0
1,@alinarosaxox I'm dead,0
2,@B13BERholic @lejlalovesbiebs omggggggg. im dead,0
3,Just got broken off. #sadlife,1
4,I lost my car keys... 😑,1
5,I lost 6 lbs and now I need a belt. #illtakeit #goodbyecollegeweight,1
6,Because I'm in need of one NOW.,2
7,I desperately need a job.. #someonehelpme #unemployedprobz,2
8,Lol i need help.,2
9,"In need of a good breakfast, im starving",3
10,it's new year's eve and i have food poisoning!! lit!!!,3
11,I think I'm in a food coma ugh,3
12,@dianafriday_ I'm heart broken 💔,4
13,@allieparker2013 sorry. Im moody :/,4
14,im lonely #andiknowit,4
15,aaaaand..... i have the flu. :/ sigh,5
16,"@istylez2 everything good bro, I'm just recovering from turkey day, how you?",5
17,Im Cramping Im Cranky &amp; its Late GoodNight✋😠💯,5
18,I haven't done anything today.....,6
19,I just puked..😔,6
20,Help! I've fallen and I can't turn up!,6

## job_search

In [37]:
df = pd.read_parquet(os.path.join(cluster_data_path, 'job_search_7_clusters.parquet'))

In [38]:
df = df.groupby('cluster', group_keys=False).apply(lambda df: df.sample(3)).reset_index(drop=True)
df[['text', 'cluster']]

,text,cluster
0,searching for a job or jobs that I can do from home.,0
1,Who hiring ? Im looking for a new job,0
2,Ima go find myself a job today 🙆🏼,0
3,Anyone goin to gorda?,1
4,I want to try some animation. Can anyone suggest good freeware?,1
5,ANYONE...I’m trying to work with watercolor paints. I cannot get things to work. Suggestions?,1
6,#breakuplines it's not you it's me I just need sometime alone...,2
7,I need some plans tonight.. hmu,2
8,I need to make some character changes.,2
9,I think this time I need to seek help before I lose my actual fucking mind completely,3
10,I need help!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!,3
11,I need someone to talk to..... anyone??,3
12,@FSTylerK I gotta find something to eat then head to the meetup.,4
13,"@NoteyUchiha See I be looking for the hood spots I’m gonna check them out though, good looks",4
14,I’m just trying to find a girl tbh😕,4
15,@sophiajunkar I need a new job asap,5
16,@_stephanopolis awww I'm sorry. But yeah I'm still looking for a job. Which sucks.,5
17,I get so depressed at work need to find a new job,5
18,I used to be on twitter heavy.. I gotta get back into it..,6
19,I need to go surfing soon,6
20,I just feel the need 2 get up and walk somewhere anyone got a destination I could try nd achieve 2night,6

In [39]:
path = '/home/manuto/Downloads/iter_0-convbert-test-48-10-900-1538433-new_samples/top_tweets/lost_job_1mo'
from glob import glob
result = [y for x in os.walk(path) for y in glob(os.path.join(x[0], '*.parquet'))]
result

['/home/manuto/Downloads/iter_0-convbert-test-48-10-900-1538433-new_samples/top_tweets/lost_job_1mo/2-gram/bed_fell/part-00000-c383c22b-dc57-45ac-87a4-b8f2ab165509-c000.snappy.parquet',
 '/home/manuto/Downloads/iter_0-convbert-test-48-10-900-1538433-new_samples/top_tweets/lost_job_1mo/2-gram/banned_got/part-00000-2524a7ed-dd80-4927-9316-876fecfd5c8a-c000.snappy.parquet',
 '/home/manuto/Downloads/iter_0-convbert-test-48-10-900-1538433-new_samples/top_tweets/lost_job_1mo/2-gram/blacked_i/part-00000-ae1d7562-da15-41e1-9100-bfd997c8b79a-c000.snappy.parquet',
 '/home/manuto/Downloads/iter_0-convbert-test-48-10-900-1538433-new_samples/top_tweets/lost_job_1mo/2-gram/lost_power/part-00000-8ebcc34f-7a74-49b5-81aa-e844c6b8796c-c000.snappy.parquet',
 '/home/manuto/Downloads/iter_0-convbert-test-48-10-900-1538433-new_samples/top_tweets/lost_job_1mo/2-gram/just_kicked/part-00000-69ee6433-3d5e-4e6a-b1cc-ba038f76fea5-c000.snappy.parquet',
 '/home/manuto/Downloads/iter_0-convbert-test-48-10-900-1538433-new_samples/top_tweets/lost_job_1mo/3-gram/my_phone_yesterday/part-00000-0d052826-b888-438c-9d6c-a7159c7ae48e-c000.snappy.parquet',
 '/home/manuto/Downloads/iter_0-convbert-test-48-10-900-1538433-new_samples/top_tweets/lost_job_1mo/3-gram/friend_lost_today/part-00000-02b0d63a-4b9b-4ffd-bf9e-5882155c77f5-c000.snappy.parquet',
 '/home/manuto/Downloads/iter_0-convbert-test-48-10-900-1538433-new_samples/top_tweets/lost_job_1mo/3-gram/for_pulled_time/part-00000-f1194d35-089f-4785-adac-ea3954455048-c000.snappy.parquet',
 '/home/manuto/Downloads/iter_0-convbert-test-48-10-900-1538433-new_samples/top_tweets/lost_job_1mo/3-gram/fucked_last_night/part-00000-54fd3e16-6107-40a2-8598-41fbaa5f22a1-c000.snappy.parquet',
 '/home/manuto/Downloads/iter_0-convbert-test-48-10-900-1538433-new_samples/top_tweets/lost_job_1mo/3-gram/got_just_kicked/part-00000-58c75127-6f7f-4db9-ade0-9f6c32df5afb-c000.snappy.parquet']

In [40]:
df = pd.concat(map(pd.read_parquet, result))
df.head()

Empty DataFrame
Columns: [tweet_id, score, text, text_lowercase, ngram]
Index: []

In [41]:
df = pd.read_parquet('/home/manuto/Downloads/iter_0-convbert-test-48-10-900-1538433-new_samples/top_tweets/lost_job_1mo/2-gram/bed_fell/part-00000-c383c22b-dc57-45ac-87a4-b8f2ab165509-c000.snappy.parquet')

In [42]:
df.head()

Empty DataFrame
Columns: [tweet_id, score, text, text_lowercase, ngram]
Index: []